services:
  bet-maker:
    build:
      context: .
      dockerfile: bet-maker/Dockerfile
    container_name: bet-maker
    ports:
      - "8001:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - line-provider
    networks:
      - backend

  line-provider:
    build:
      context: .
      dockerfile: line-provider/Dockerfile
    container_name: line-provider
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
